name = "SPARKx509"
description = "Verified library for X.509 certificates"
version = "0.0.1"

authors = ["Jon Andrew"]
maintainers = ["Jon Andrew <doc@swapgs.com>"]
maintainers-logins = ["docandrew"]
