name = "sparkx509"
description = "Verified library for X.509 certificates"
version = "0.0.1"

authors = ["Jon Andrew"]
maintainers = ["Jon Andrew <doc@fastmail.com>"]
maintainers-logins = ["docandrew"]
[[depends-on]]
gnatprove = "^12.1.1"
