pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "unit ""adaasn1rtl"" is not referenced");
with adaasn1rtl;
pragma Warnings (Off, "unit ""adaasn1rtl"" is not referenced");
--with PKIX1Explicit88;


pragma Warnings (Off, "no entities of ""PKIX1Explicit88"" are referenced");
pragma Warnings (Off, "unit ""PKIX1Explicit88"" is not referenced");
with PKIX1Explicit88;
pragma Warnings (On, "no entities of ""PKIX1Explicit88"" are referenced");
pragma Warnings (On, "unit ""PKIX1Explicit88"" is not referenced");


package PKIX1Explicit88_auto_tcs
is


end PKIX1Explicit88_auto_tcs;